// JSFFScript.js
(function(){
Type.registerNamespace('JSFFScript');JSFFScript.Friend=function(_response,_canvasContext){this.name=_response.name;this.id=_response.id;this.$0=_canvasContext;this.connections=[];var $0=document.createElement('img');$0.src='http://graph.facebook.com/'+this.id+'/picture';$0.id=this.get_imageid();$0.style.visibility='hidden';document.getElementById('images').insertBefore($0);}
JSFFScript.Friend.prototype={$0:null,name:null,id:null,connections:null,get_imageid:function(){return 'image'+this.id;},get_getImageElement:function(){return document.getElementById(this.get_imageid());},drawImage:function(_x,_y){this.$0.drawImage(this.get_getImageElement(),_x,_y);}}
JSFFScript._FFJS=function(){}
JSFFScript._FFJS.$3=function($p0){var $0={};$0.scope='email, user_likes, publish_stream';FB.login(function($p1_0){
},$0);}
JSFFScript._FFJS.$4=function($p0){var $0={};FB.api('/me/friends',function($p1_0){
var $1_0=document.getElementById('tutorial');var $1_1=$1_0.getContext('2d');for(var $1_4=0;$1_4<$p1_0.data.length;$1_4++){var $1_5=new JSFFScript.Friend($p1_0.data[$1_4],$1_1);JSFFScript._FFJS.$1[$1_5.id]=$1_5;}var $1_2={};$1_2.friendsLimit='SELECT uid1, uid2 from friend WHERE uid1 = '+JSFFScript._FFJS.$0+' ORDER BY uid2';$1_2.friendsAll='SELECT uid1, uid2 from friend WHERE uid1 = '+JSFFScript._FFJS.$0;$1_2.friendsoffriends='SELECT uid1, uid2 FROM friend WHERE uid1 IN (SELECT uid2 from #friendsLimit) AND uid2 IN (SELECT uid2 from #friendsAll) AND uid1 < uid2';var $1_3={};$1_3.method='fql.multiquery';$1_3.queries=$1_2;FB.api($1_3,function($p2_0){
if(JSFFScript._FFJS.$2){alert($p2_0[2].fql_result_set.length);}for(var $2_0=0;$2_0<$p2_0[2].fql_result_set.length;$2_0++){var $2_1=$p2_0[2].fql_result_set[$2_0];(JSFFScript._FFJS.$1[$2_1.uid1]).connections.add($2_1.uid2);(JSFFScript._FFJS.$1[$2_1.uid2]).connections.add($2_1.uid1);}if(JSFFScript._FFJS.$2){alert(Object.getKeyCount(JSFFScript._FFJS.$1));}});for(var $1_6=0;$1_6<Object.keys(JSFFScript._FFJS.$1).length;$1_6++){var $1_7=JSFFScript._FFJS.$1[Object.keys(JSFFScript._FFJS.$1)[$1_6]];var $1_8=Math.floor($1_6/20)*50;var $1_9=Math.floor($1_6%20)*50;$1_7.drawImage($1_9,$1_8);}});}
JSFFScript._FFJS.$5=function($p0){FB.logout(function(){
});(document.getElementById('image')).src='';$('#resultsDiv').html('');}
JSFFScript._FFJS.$6=function(){$('#MyButton').click(JSFFScript._FFJS.$3);$('#PostButton').click(JSFFScript._FFJS.$4);$('#LogoutButton').click(JSFFScript._FFJS.$5);var $0={};$0.appId='240082229369859';$0.channelUrl='//limeyhouse.dyndns.org/channel.aspx';$0.status=true;$0.cookie=true;$0.xfbml=false;FB.init($0);FB.getLoginStatus(function($p1_0){
if($p1_0.status==='connected'){JSFFScript._FFJS.$0=$p1_0.authResponse.userID;(document.getElementById('image')).src='http://graph.facebook.com/'+JSFFScript._FFJS.$0+'/picture';}});FB.Event.subscribe('auth.authResponseChange',function($p1_0){
if(JSFFScript._FFJS.$2){alert('Event Login Fired');}if($p1_0.status==='connected'){JSFFScript._FFJS.$0=$p1_0.userID;(document.getElementById('image')).src='http://graph.facebook.com/'+$p1_0.userID+'/picture';}else{alert('Not Logged in ');}});}
JSFFScript.Friend.registerClass('JSFFScript.Friend');JSFFScript._FFJS.registerClass('JSFFScript._FFJS');JSFFScript._FFJS.$0=null;JSFFScript._FFJS.$1={};JSFFScript._FFJS.$2=false;(function(){$(JSFFScript._FFJS.$6);})();
})();// This script was generated using Script# v0.7.4.0
