// JSFFScript.js
(function(){
Type.registerNamespace('JSFFScript');JSFFScript._FFJS=function(){}
JSFFScript._FFJS.$A=function($p0){var $0={};$0.scope='email, user_likes, publish_stream';FB.login(function($p1_0){
},$0);}
JSFFScript._FFJS.$B=function($p0){JSFFScript._FFJS.$D();var $0={};FB.api('/me/friends',function($p1_0){
JSFFScript._FFJS.$C($p1_0.data.length);for(var $1_2=0;$1_2<$p1_0.data.length;$1_2++){var $1_3=(Math.floor($1_2%JSFFScript._FFJS.$2)*(JSFFScript._FFJS.$0+JSFFScript._FFJS.$1))+JSFFScript._FFJS.$1;var $1_4=(Math.floor($1_2/JSFFScript._FFJS.$2)*(JSFFScript._FFJS.$0+JSFFScript._FFJS.$1))+JSFFScript._FFJS.$1;var $1_5=new JSFFScript.Friend($p1_0.data[$1_2],JSFFScript._FFJS.$9,parseInt($1_3),parseInt($1_4));JSFFScript._FFJS.$5[$1_5.id]=$1_5;}var $1_0={};$1_0.friendsLimit='SELECT uid1, uid2 from friend WHERE uid1 = '+JSFFScript._FFJS.$4+' ORDER BY uid2';$1_0.friendsAll='SELECT uid1, uid2 from friend WHERE uid1 = '+JSFFScript._FFJS.$4;$1_0.friendsoffriends='SELECT uid1, uid2 FROM friend WHERE uid1 IN (SELECT uid2 from #friendsLimit) AND uid2 IN (SELECT uid2 from #friendsAll) AND uid1 < uid2';var $1_1={};$1_1.method='fql.multiquery';$1_1.queries=$1_0;FB.api($1_1,function($p2_0){
if(JSFFScript._FFJS.$6){alert($p2_0[2].fql_result_set.length);}for(var $2_0=0;$2_0<$p2_0[2].fql_result_set.length;$2_0++){var $2_1=$p2_0[2].fql_result_set[$2_0];(JSFFScript._FFJS.$5[$2_1.uid1]).connections.add($2_1.uid2);(JSFFScript._FFJS.$5[$2_1.uid2]).connections.add($2_1.uid1);}if(JSFFScript._FFJS.$6){alert(Object.getKeyCount(JSFFScript._FFJS.$5));}});});$('#tutorial').mousemove(JSFFScript._FFJS.$10);$('#tutorial').click(JSFFScript._FFJS.$F);}
JSFFScript._FFJS.$C=function($p0){var $0=JSFFScript._FFJS.$7.width;JSFFScript._FFJS.$2=Math.ceil(Math.sqrt($p0));JSFFScript._FFJS.$0=(($0-JSFFScript._FFJS.$1)/JSFFScript._FFJS.$2)-JSFFScript._FFJS.$1;}
JSFFScript._FFJS.$D=function(){JSFFScript._FFJS.$9.save();JSFFScript._FFJS.$9.setTransform(1,0,0,1,0,0);JSFFScript._FFJS.$9.clearRect(0,0,JSFFScript._FFJS.$7.width,JSFFScript._FFJS.$7.height);JSFFScript._FFJS.$9.restore();}
JSFFScript._FFJS.$E=function($p0){FB.logout(function(){
});}
JSFFScript._FFJS.$F=function($p0){JSFFScript._FFJS.$D();JSFFScript._FFJS.$14();var $0=JSFFScript._FFJS.$11($p0);if(ss.isNullOrUndefined($0)){return;}JSFFScript._FFJS.$12($0);}
JSFFScript._FFJS.$10=function($p0){var $0=JSFFScript._FFJS.$11($p0);var $1='';if(!ss.isNullOrUndefined($0)){$1=$0.name;}$('#friendName').text($1);}
JSFFScript._FFJS.$11=function($p0){for(var $0=0;$0<Object.keys(JSFFScript._FFJS.$5).length;$0++){var $1=JSFFScript._FFJS.$5[Object.keys(JSFFScript._FFJS.$5)[$0]];if($1.get_x()<$p0.offsetX&&($1.get_x()+JSFFScript._FFJS.$0)>$p0.offsetX&&$1.get_y()<$p0.offsetY&&($1.get_y()+JSFFScript._FFJS.$0)>$p0.offsetY){return $1;}}return null;}
JSFFScript._FFJS.$12=function($p0){for(var $0=0;$0<$p0.connections.length;$0++){var $1=JSFFScript._FFJS.$5[$p0.connections[$0]];$1.highlightSecondary();}$p0.highlightPrimary();}
JSFFScript._FFJS.$13=function($p0,$p1){JSFFScript._FFJS.$9.beginPath();JSFFScript._FFJS.$9.moveTo($p0.get_x(),$p0.get_y());JSFFScript._FFJS.$9.lineTo($p1.get_x(),$p1.get_y());JSFFScript._FFJS.$9.closePath();JSFFScript._FFJS.$9.stroke();}
JSFFScript._FFJS.$14=function(){for(var $0=0;$0<Object.keys(JSFFScript._FFJS.$5).length;$0++){var $1=JSFFScript._FFJS.$5[Object.keys(JSFFScript._FFJS.$5)[$0]];$1.drawImage();}}
JSFFScript._FFJS.$15=function($p0){JSFFScript._FFJS.$8=new JSFFScript.FriendsGroup(JSFFScript._FFJS.$5);JSFFScript._FFJS.$16();}
JSFFScript._FFJS.$16=function(){var $0=Object.keys(JSFFScript._FFJS.$5)[JSFFScript._FFJS.$3%Object.keys(JSFFScript._FFJS.$5).length];JSFFScript._FFJS.$8.iterateSingle($0);JSFFScript._FFJS.$D();JSFFScript._FFJS.$14();JSFFScript._FFJS.$3++;if(JSFFScript._FFJS.$3<1000){window.setTimeout(JSFFScript._FFJS.$16,50);}}
JSFFScript._FFJS.$17=function(){JSFFScript._FFJS.$7=document.getElementById('tutorial');JSFFScript._FFJS.$9=JSFFScript._FFJS.$7.getContext('2d');$('#login').click(JSFFScript._FFJS.$A);$('#graph').click(JSFFScript._FFJS.$B);$('#LogoutButton').click(JSFFScript._FFJS.$E);$('#Iterate').click(JSFFScript._FFJS.$15);var $0={};$0.appId='459808530803920';$0.channelUrl='http://localhost/channel.aspx';$0.status=true;$0.cookie=true;$0.xfbml=false;FB.init($0);FB.getLoginStatus(function($p1_0){
if($p1_0.status==='connected'){JSFFScript._FFJS.$4=$p1_0.authResponse.userID;(document.getElementById('image')).src='http://graph.facebook.com/'+JSFFScript._FFJS.$4+'/picture';}});FB.Event.subscribe('auth.authResponseChange',function($p1_0){
if(JSFFScript._FFJS.$6){alert('Event Login Fired');}if($p1_0.status==='connected'){JSFFScript._FFJS.$4=$p1_0.authResponse.userID;(document.getElementById('image')).src='http://graph.facebook.com/'+JSFFScript._FFJS.$4+'/picture';}else{(document.getElementById('image')).src='';JSFFScript._FFJS.$D();}});}
JSFFScript.Friend=function(_response,_canvasContext,_x,_y){this.name=_response.name;this.id=_response.id;this.$0=_canvasContext;this.position=new JSFFScript.Point();this.position.x=_x;this.position.y=_y;this.connections=[];var $0=document.createElement('img');$0.src='http://graph.facebook.com/'+this.id+'/picture';$0.id=this.get_imageid();$0.style.visibility='hidden';document.getElementById('images').insertBefore($0);$('#'+this.get_imageid()).one('load',ss.Delegate.create(this,this.drawLoadImage));}
JSFFScript.Friend.prototype={$0:null,name:null,position:null,id:null,connections:null,get_imageid:function(){return 'image'+this.id;},get_getImageElement:function(){return document.getElementById(this.get_imageid());},highlightPrimary:function(){this.$0.fillStyle='red';this.$0.fillRect(this.get_x()-JSFFScript._FFJS.$1,this.get_y()-JSFFScript._FFJS.$1,JSFFScript._FFJS.$1*2+JSFFScript._FFJS.$0,JSFFScript._FFJS.$1*2+JSFFScript._FFJS.$0);this.drawImage();},highlightSecondary:function(){this.$0.fillStyle='green';this.$0.fillRect(this.get_x()-JSFFScript._FFJS.$1,this.get_y()-JSFFScript._FFJS.$1,JSFFScript._FFJS.$1*2+JSFFScript._FFJS.$0,JSFFScript._FFJS.$1*2+JSFFScript._FFJS.$0);this.drawImage();},drawLoadImage:function(e){this.drawImage();},drawImage:function(){this.$0.drawImage(this.get_getImageElement(),this.get_x(),this.get_y(),JSFFScript._FFJS.$0,JSFFScript._FFJS.$0);},get_x:function(){return this.position.x;},set_x:function(value){this.position.x=value;return value;},get_y:function(){return this.position.y;},set_y:function(value){this.position.y=value;return value;}}
JSFFScript.FriendsGroup=function(_Friends){this.friends=_Friends;this.vertexCount=Object.keys(_Friends).length;}
JSFFScript.FriendsGroup.prototype={friends:null,repulsionConstant:0.01,attractionConstant:0.01,vertexCount:0,$0:function($p0,$p1){var $0=this.$2($p0.get_x(),$p0.get_y(),$p1.get_x(),$p1.get_y());var $1=($p0.get_x()-$p1.get_x())/$0;var $2=($p0.get_y()-$p1.get_y())/$0;var $3=new JSFFScript.Vector(0,0);$3.xCord=$1/(this.repulsionConstant*$0*$0);$3.yCord=$2/(this.repulsionConstant*$0*$0);return $3;},$1:function($p0,$p1){var $0=new JSFFScript.Vector(0,0);$0.xCord=this.attractionConstant*($p1.get_x()-$p0.get_x());$0.yCord=this.attractionConstant*($p1.get_y()-$p0.get_y());return $0;},$2:function($p0,$p1,$p2,$p3){var $0=Math.sqrt(Math.pow($p2-$p0,2)+Math.pow($p3,$p1));return $0;},iterate:function(){for(var $0=0;$0<Object.keys(this.friends).length;$0++){this.iterateSingle(Object.keys(this.friends)[$0]);}},iterateSingle:function(id){var $0=this.friends[id];var $1=new JSFFScript.Vector(0,0);for(var $2=0;$2<Object.keys(this.friends).length;$2++){var $3=this.friends[Object.keys(this.friends)[$2]];if($0.id!==$3.id){if($0.connections.contains($3.id)){$1.add(this.$1($0,$3));}else{$1.add(this.$0($0,$3));}}}$0.set_x($0.get_x()+parseInt($1.xCord));$0.set_y($0.get_y()+parseInt($1.yCord));}}
JSFFScript.Vector=function(X,Y){this.xCord=X;this.yCord=Y;}
JSFFScript.Vector.prototype={xCord:0,yCord:0,add:function(add){this.xCord+=add.xCord;this.yCord+=add.yCord;}}
JSFFScript.Point=function(){}
JSFFScript.Point.prototype={x:0,y:0,addVector:function(v){this.x+=parseInt(v.xCord);this.y+=parseInt(v.yCord);}}
JSFFScript._FFJS.registerClass('JSFFScript._FFJS');JSFFScript.Friend.registerClass('JSFFScript.Friend');JSFFScript.FriendsGroup.registerClass('JSFFScript.FriendsGroup');JSFFScript.Vector.registerClass('JSFFScript.Vector');JSFFScript.Point.registerClass('JSFFScript.Point');JSFFScript._FFJS.$0=0;JSFFScript._FFJS.$1=10;JSFFScript._FFJS.$2=0;JSFFScript._FFJS.$3=0;JSFFScript._FFJS.$4=null;JSFFScript._FFJS.$5={};JSFFScript._FFJS.$6=false;JSFFScript._FFJS.$7=null;JSFFScript._FFJS.$8=null;JSFFScript._FFJS.$9=null;(function(){$(JSFFScript._FFJS.$17);})();
})();// This script was generated using Script# v0.7.4.0
